# Generated by Django 4.0.4 on 2022-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_recipe_author_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(upload_to='recipes/covers/%Y/%m/%d'),
        ),
    ]
