# Generated by Django 4.0.4 on 2022-05-14 23:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_category_alter_recipe_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
