# Generated by Django 4.0.4 on 2022-05-28 16:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=165),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_steps',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_steps_is_html',
            field=models.BooleanField(default=True),
        ),
    ]
