# Generated by Django 4.0.4 on 2022-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='recipes/covers/%Y/%m/%d'),
        ),
    ]
